"""launchd WatchPaths 守护：监听 run.py 变化，自动重打补丁 + 重启网关.

hermes 自动升级会覆盖 gateway/run.py 清掉 AST hook，本插件装一个 launchd job
监听 run.py 变化，一变就自动 ``uninstall && install && kickstart``。配合 register()
启动时自愈形成双保险。由 install/uninstall 命令自动装/卸，用户无需手动管理。
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .config import hermes_home
from .patcher import hermes_install_dir, hermes_python

LABEL = "com.hermes-lark.watchdog"


def _launch_agents_dir() -> Path:
    return Path.home() / "Library" / "LaunchAgents"


def plist_path() -> Path:
    return _launch_agents_dir() / f"{LABEL}.plist"


def _watched_run_py() -> Path:
    """守护监听的 run.py 路径（hermes 安装目录下）."""
    install_dir = hermes_install_dir()
    if install_dir is not None:
        p = install_dir / "gateway" / "run.py"
        if p.exists():
            return p
    return hermes_home() / "hermes-agent" / "gateway" / "run.py"


def _repatch_script_path() -> Path:
    """防抖重打脚本路径（装到 ~/.hermes/ 下，launchd ProgramArguments 指向它）."""
    return hermes_home() / ".hermes_lark_watchdog.sh"


@dataclass
class WatchdogStatus:
    installed: bool
    plist: Path
    loaded: bool


def status() -> WatchdogStatus:
    p = plist_path()
    loaded = False
    if shutil.which("launchctl") is not None:
        # launchctl list <label> 优先（取裸 label，无需拼 gui/<uid>/ 域，更少移动部件）；
        # 回退 launchctl print gui/<uid>/<label>（与 install() 的 bootstrap 同源 API）。
        # 两者任一 exit 0 即视为已加载。WatchPaths job 在 idle 时 state=not running
        # 但仍已注册，exit 0。
        for args in (
            ["launchctl", "list", LABEL],
            ["launchctl", "print", f"gui/{os.getuid()}/{LABEL}"],
        ):
            try:
                result = subprocess.run(
                    args, capture_output=True, timeout=5,
                )
                if result.returncode == 0 and result.stdout.strip():
                    loaded = True
                    break
            except (OSError, subprocess.SubprocessError):
                continue
    return WatchdogStatus(installed=p.exists(), plist=p, loaded=loaded)


def _render_repatch_script() -> str:
    """生成防抖重打脚本：run.py 一变，等 5s 收尾再 uninstall+install+kickstart.

    用 mtime 文件做防抖：若 5s 内已重打过则跳过（避免 hermes 更新多次触发）。
    升级重建 venv 会丢掉插件 editable 安装，故在重打 patch 前先确保插件在 venv 里。
    """
    py = hermes_python()
    py_str = str(py) if py else "/usr/bin/python3"
    home = str(hermes_home())
    label = os.environ.get("HERMES_LARK_LAUNCHD_LABEL", "ai.hermes.gateway")
    # 源码目录在生成时解析注入（脚本需独立可执行，不能运行时 import 本模块）。
    from ._source import source_dir

    src = source_dir()
    src_str = str(src) if src is not None else ""
    # 源码目录校验通过才生成重装段；否则跳过（仅靠 register() 自愈兜底）。
    reinstall_snippet = ""
    if src is not None:
        # find_spec 检测写成独立 helper 行，避免 heredoc 单行过长。
        check_cmd = (
            '"$PY" -c "import importlib.util as u; import sys; '
            "sys.exit(0 if u.find_spec('hermes_lark_streaming') else 1)\""
        )
        reinstall_snippet = (
            f'# 确保插件在 venv（升级重建 venv 会丢 editable 安装）；失败不阻塞 patch\n'
            f'if ! {check_cmd} 2>/dev/null; then\n'
            f'  "$PY" -m pip install -e {shlex.quote(src_str)} '
            f'-i https://pypi.tuna.tsinghua.edu.cn/simple '
            f'--timeout 30 --no-build-isolation >/dev/null 2>&1 || true\n'
            f'fi\n'
        )
    return f"""#!/bin/bash
# AUTO-GENERATED by hermes-lark-streaming. launchd WatchPaths 守护调用此脚本。
# run.py 变化 → 防抖 5s → 重打补丁 → kickstart 网关（让补丁版重新加载）。
set -e
export HERMES_HOME={shlex.quote(home)}
PY={shlex.quote(py_str)}
STAMP={shlex.quote(home)}/.hermes_lark_watchdog.stamp
# 防抖：距上次重打 < 10s 则跳过
if [ -f "$STAMP" ]; then
  now=$(date +%s); last=$(cat "$STAMP" 2>/dev/null || echo 0)
  if [ $((now - last)) -lt 10 ]; then exit 0; fi
fi
date +%s > "$STAMP"
echo "[hermes-lark-watchdog] $(date '+%H:%M:%S') run.py changed — re-patching"
{reinstall_snippet}# 先卸（清旧 marker + 还原守卫），再装（含 bg_watcher）
"$PY" -m hermes_lark_streaming uninstall >/dev/null 2>&1 || true
"$PY" -m hermes_lark_streaming install >/dev/null 2>&1 || true
# kickstart 让网关带补丁重启
if command -v launchctl >/dev/null 2>&1; then
  launchctl kickstart "gui/$(id -u)/{label}" 2>/dev/null || true
fi
"""


def _render_plist(script_path: Path, watch_target: Path) -> str:
    """生成 launchd plist（WatchPaths 监听 run.py）."""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{script_path}</string>
    </array>
    <key>WatchPaths</key>
    <array>
        <string>{watch_target}</string>
    </array>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>{hermes_home()}/logs/hermes_lark_watchdog.log</string>
    <key>StandardErrorPath</key>
    <string>{hermes_home()}/logs/hermes_lark_watchdog.log</string>
</dict>
</plist>
"""


def _domain_target() -> str:
    return f"gui/{os.getuid()}"


def install() -> bool:
    """装守护脚本 + plist 并 load。返回 True 表示成功（或已装）.

    用现代 ``launchctl bootstrap`` API（macOS 10.10+，darwin 15 上 ``load`` 不可靠），
    bootstrap 失败时回退 bootout 再 bootstrap，再不行回退旧 load。
    """
    if shutil.which("launchctl") is None:
        return False
    launch_dir = _launch_agents_dir()
    launch_dir.mkdir(parents=True, exist_ok=True)

    script = _repatch_script_path()
    script.write_text(_render_repatch_script(), encoding="utf-8")
    script.chmod(0o755)

    watch_target = _watched_run_py()
    plist = plist_path()
    plist.write_text(_render_plist(script, watch_target), encoding="utf-8")

    domain = _domain_target()
    # 先 bootout（已加载则卸载，幂等），再 bootstrap 刷新
    subprocess.run(
        ["launchctl", "bootout", f"{domain}/{LABEL}"], capture_output=True, timeout=10
    )
    result = subprocess.run(
        ["launchctl", "bootstrap", domain, str(plist)],
        capture_output=True,
        text=True,
        timeout=10,
    )
    if result.returncode == 0:
        return True
    # 回退旧 load API（老 macOS 或 bootstrap 语义差异）
    subprocess.run(["launchctl", "unload", str(plist)], capture_output=True, timeout=10)
    fallback = subprocess.run(
        ["launchctl", "load", str(plist)], capture_output=True, text=True, timeout=10
    )
    return fallback.returncode == 0


def uninstall() -> bool:
    """卸守护：bootout + 删 plist + 删脚本."""
    if shutil.which("launchctl") is None:
        return False
    domain = _domain_target()
    plist = plist_path()
    if plist.exists():
        subprocess.run(
            ["launchctl", "bootout", f"{domain}/{LABEL}"], capture_output=True, timeout=10
        )
        subprocess.run(["launchctl", "unload", str(plist)], capture_output=True, timeout=10)
        plist.unlink(missing_ok=True)
    script = _repatch_script_path()
    script.unlink(missing_ok=True)
    return True
